In [1]:
import os
os.environ['OMP_NUM_THREADS'] = '1'

In [2]:
import pandas as pd

In [3]:
from sklearn.cluster import KMeans
from sklearn.ensemble import RandomForestClassifier

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

---

In [5]:
# Step 1: Create Dataset

data = pd.DataFrame({
    "Age": [20, 22, 25, 30, 35, 40, 45, 50, 28, 32],
    "MonthlyIncome": [
        25000, 30000, 35000, 60000, 70000,
        85000, 90000, 100000, 50000, 65000
    ],
    "TimeSpentOnApp": [
        15, 20, 25, 50, 55,
        60, 70, 80, 40, 45
    ],
    "TotalPurchases": [
        2, 3, 4, 10, 12,
        15, 18, 20, 8, 9
    ],
    "PremiumMembership": [
        0, 0, 0, 1, 1,
        1, 1, 1, 0, 1
    ]
})

In [6]:
data

   Age  MonthlyIncome  TimeSpentOnApp  TotalPurchases  PremiumMembership
0   20          25000              15               2                  0
1   22          30000              20               3                  0
2   25          35000              25               4                  0
3   30          60000              50              10                  1
4   35          70000              55              12                  1
5   40          85000              60              15                  1
6   45          90000              70              18                  1
7   50         100000              80              20                  1
8   28          50000              40               8                  0
9   32          65000              45               9                  1

---

In [7]:
# Step 2: Features and Target

X = data[[
    "Age",
    "MonthlyIncome",
    "TimeSpentOnApp",
    "TotalPurchases"
]]

y = data["PremiumMembership"]

---

In [8]:
# Step 3: K-Means Clustering

kmeans = KMeans(
    n_clusters=4,
    random_state=42
)

kmeans = kmeans.fit(X)

In [9]:
# Add cluster column

data["Cluster"] = kmeans.labels_

In [10]:
# Add cluster to features

X = X.copy()
X["Cluster"] = data["Cluster"]

---

In [11]:
# Step 4: Split Dataset

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

---

In [12]:
# Step 5: Train Model

model = RandomForestClassifier(

    n_estimators=100,
    random_state=42

)

model = model.fit(X_train, y_train)

---

In [13]:
# Step 6: Prediction

y_pred = model.predict(X_test)

---

In [14]:
# Step 7: Evaluation

accuracy = accuracy_score(y_test, y_pred)

cm = confusion_matrix(y_test, y_pred)

print("\nCustomer Clusters:")
print(data[["Age", "MonthlyIncome", "Cluster"]])

Customer Clusters:
   Age  MonthlyIncome  Cluster
0   20          25000        2
1   22          30000        2
2   25          35000        2
3   30          60000        0
4   35          70000        0
5   40          85000        1
6   45          90000        1
7   50         100000        3
8   28          50000        0
9   32          65000        0

In [15]:
print(f"Accuracy: {accuracy}")

print("\nConfusion Matrix:")

print(cm)

Accuracy: 0.5

Confusion Matrix:
[[1 1]
 [0 0]]

---

In [16]:
# Step 8: Predict New Customer

new_customer = pd.DataFrame({
    "Age": [33],
    "MonthlyIncome": [75000],
    "TimeSpentOnApp": [58],
    "TotalPurchases": [14]
})

In [17]:
new_customer

   Age  MonthlyIncome  TimeSpentOnApp  TotalPurchases
0   33          75000              58              14

In [18]:
# Find cluster of new customer

new_cluster = kmeans.predict(new_customer)

new_customer["Cluster"] = new_cluster

prediction = model.predict(new_customer)

In [19]:
print("Prediction for New Customer:")

if prediction[0] == 1:
    print("Premium Membership: YES")
else:
    print("Premium Membership: NO")

Prediction for New Customer:
Premium Membership: YES