# Data Transformation

Once your data is clean, the next step is to **reshape, reformat, and reorder** it as needed for analysis. Pandas gives you plenty of flexible tools to do this.

---

## Sorting & Ranking

### Sort by Values

```python
df.sort_values("Age")                   # Ascending sort
df.sort_values("Age", ascending=False)  # Descending
df.sort_values(["Age", "Salary"])       # Sort by multiple columns
```
df.sort_values(["Age", "Salary"]) sorts the DataFrame first by the "Age" column, and if there are ties (i.e., two or more rows with the same "Age"), it will sort by the "Salary" column.

### Reset Index
If you want the index to start from 0 and be sequential, you can reset it using reset_index()
```python
df.reset_index(drop=True, inplace=True)  # Reset the index and drop the old index
```
### Sort by Index

```python
df.sort_index()
```
The df.sort_index() function is used to sort the DataFrame based on its index values. If the index is not in a sequential order (e.g., you have dropped rows or performed other operations that change the index), you can use sort_index() to restore it to a sorted order.
### Ranking
The .rank() function in pandas is used to assign ranks to numeric values in a column, like scores or points. By default, it gives the average rank to tied values, which can result in decimal numbers. For example, if two people share the top score, they both get a rank of 1.5. You can customize the ranking behavior using the method parameter. One useful option is method='dense', which assigns the same rank to ties but doesn’t leave gaps in the ranking sequence. This is helpful when you want a clean, consecutive ranking system without skips.
```python
df["Rank"] = df["Score"].rank()                 # Default: average method
df["Rank"] = df["Score"].rank(method="dense")   # 1, 2, 2, 3
```

---

## Renaming Columns & Index

```python
df.rename(columns={"oldName": "newName"}, inplace=True)
df.rename(index={0: "row1", 1: "row2"}, inplace=True)
```

To rename all columns:

```python
df.columns = ["Name", "Age", "City"]
```

---

## Changing Column Order

Just pass a new list of column names:

```python
df = df[["City", "Name", "Age"]]   # Reorder as desired
```

You can also move one column to the front:

```python
cols = ["Name"] + [col for col in df.columns if col != "Name"]
df = df[cols]
```

---



## Summary

- Sort, rank, and rename to prepare your data    
- Reordering and reshaping are key for EDA and visualization

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data2.csv")

In [3]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

## Sort by Values

In [4]:
df.sort_values('Year')

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

In [7]:
df.sort_values('Year', ascending=False)

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
2,Aamir Khan,Dangal,2016,Biography,2024,8.4

## Reset Index

In [10]:
df2 = df.sort_values(['Year', 'IMDb']).copy()

In [16]:
df2.reset_index(drop=True)

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
3,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
4,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Hrithik Roshan,War,2019,Action,475,6.5
7,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
8,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
9,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
10,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
11,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

In [17]:
df2

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

In [19]:
df2.reset_index(drop=True, inplace=True)

In [20]:
df2

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
3,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
4,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Hrithik Roshan,War,2019,Action,475,6.5
7,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
8,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
9,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
10,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
11,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

## Sort by Index

In [26]:
df3 = df.sort_values(['Year', 'BoxOffice(INR Crore)']).copy()

In [27]:
df3

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
7,Hrithik Roshan,War,2019,Action,475,6.5
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

In [28]:
df3.sort_index()

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

## Ranking

In [30]:
df2

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
3,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
4,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Hrithik Roshan,War,2019,Action,475,6.5
7,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
8,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
9,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
10,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
11,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

In [35]:
df2['Rank'] = df2['IMDb'].rank(ascending=False, method='dense')

In [37]:
df2

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb,Rank
0,Aamir Khan,Dangal,2016,Biography,2024,8.4,1.0
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,9.0
2,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,8.0
3,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.0
4,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,4.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,2.0
6,Hrithik Roshan,War,2019,Action,475,6.5,7.0
7,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.0
8,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,3.0
9,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,11.0
10,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,10.0
11,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,5.0

In [44]:
df2['Rank By Collection'] = df2['BoxOffice(INR Crore)'].rank(ascending=False, method='dense')

In [46]:
df2

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb,Rank,Rank By Collection
0,Aamir Khan,Dangal,2016,Biography,2024,8.4,1.0,1.0
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,9.0,4.0
2,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,8.0,10.0
3,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.0,3.0
4,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,4.0,11.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,2.0,12.0
6,Hrithik Roshan,War,2019,Action,475,6.5,7.0,5.0
7,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.0,8.0
8,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,3.0,7.0
9,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,11.0,6.0
10,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,10.0,9.0
11,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,5.0,2.0

## Renaming Columns & Index

In [47]:
df2.rename(columns={"Rank": 'Rank By IMDb'}, inplace=True)

In [48]:
df2

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb,Rank By IMDb,Rank By Collection
0,Aamir Khan,Dangal,2016,Biography,2024,8.4,1.0,1.0
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,9.0,4.0
2,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,8.0,10.0
3,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.0,3.0
4,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,4.0,11.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,2.0,12.0
6,Hrithik Roshan,War,2019,Action,475,6.5,7.0,5.0
7,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.0,8.0
8,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,3.0,7.0
9,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,11.0,6.0
10,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,10.0,9.0
11,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,5.0,2.0

In [50]:
df2.rename(index={0: 'row1', 1: 'row2'})

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb,Rank By IMDb,Rank By Collection
row1,Aamir Khan,Dangal,2016,Biography,2024,8.4,1.0,1.0
row2,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,9.0,4.0
2,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,8.0,10.0
3,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.0,3.0
4,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,4.0,11.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,2.0,12.0
6,Hrithik Roshan,War,2019,Action,475,6.5,7.0,5.0
7,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.0,8.0
8,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,3.0,7.0
9,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,11.0,6.0
10,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,10.0,9.0
11,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,5.0,2.0

In [51]:
df2

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb,Rank By IMDb,Rank By Collection
0,Aamir Khan,Dangal,2016,Biography,2024,8.4,1.0,1.0
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,9.0,4.0
2,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,8.0,10.0
3,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.0,3.0
4,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,4.0,11.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,2.0,12.0
6,Hrithik Roshan,War,2019,Action,475,6.5,7.0,5.0
7,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.0,8.0
8,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,3.0,7.0
9,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,11.0,6.0
10,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,10.0,9.0
11,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,5.0,2.0

## Changing Column Order

In [53]:
df2 = df2[['Film', 'Year', 'Actor', 'Genre', 'IMDb', 'BoxOffice(INR Crore)', 'Rank By Collection', 'Rank By IMDb']]

In [54]:
df2

,Film,Year,Actor,Genre,IMDb,BoxOffice(INR Crore),Rank By Collection,Rank By IMDb
0,Dangal,2016,Aamir Khan,Biography,8.4,2024,1.0,1.0
1,Tiger Zinda Hai,2017,Salman Khan,Action,6.0,565,4.0,9.0
2,Badrinath Ki Dulhania,2017,Varun Dhawan,Romantic Comedy,6.1,201,10.0,8.0
3,Padmaavat,2018,Ranveer Singh,Historical,7.0,585,3.0,6.0
4,Stree,2018,Rajkummar Rao,Horror Comedy,7.5,180,11.0,4.0
5,Andhadhun,2018,Ayushmann Khurrana,Thriller,8.3,111,12.0,2.0
6,War,2019,Hrithik Roshan,Action,6.5,475,5.0,7.0
7,Good Newwz,2019,Akshay Kumar,Comedy,7.0,318,8.0,6.0
8,Uri: The Surgical Strike,2019,Vicky Kaushal,Action,8.2,342,7.0,3.0
9,Brahmastra,2022,Ranbir Kapoor,Fantasy,5.6,431,6.0,11.0
10,Bhool Bhulaiyaa 2,2022,Kartik Aaryan,Horror Comedy,5.9,266,9.0,10.0
11,Pathaan,2023,Shah Rukh Khan,Action,7.2,1050,2.0,5.0

In [57]:
cols = ['Year'] + [col for col in df.columns if col != 'Year']
df2 = df2[cols]

In [58]:
df2

,Year,Actor,Film,Genre,BoxOffice(INR Crore),IMDb
0,2016,Aamir Khan,Dangal,Biography,2024,8.4
1,2017,Salman Khan,Tiger Zinda Hai,Action,565,6.0
2,2017,Varun Dhawan,Badrinath Ki Dulhania,Romantic Comedy,201,6.1
3,2018,Ranveer Singh,Padmaavat,Historical,585,7.0
4,2018,Rajkummar Rao,Stree,Horror Comedy,180,7.5
5,2018,Ayushmann Khurrana,Andhadhun,Thriller,111,8.3
6,2019,Hrithik Roshan,War,Action,475,6.5
7,2019,Akshay Kumar,Good Newwz,Comedy,318,7.0
8,2019,Vicky Kaushal,Uri: The Surgical Strike,Action,342,8.2
9,2022,Ranbir Kapoor,Brahmastra,Fantasy,431,5.6
10,2022,Kartik Aaryan,Bhool Bhulaiyaa 2,Horror Comedy,266,5.9
11,2023,Shah Rukh Khan,Pathaan,Action,1050,7.2