# Merging & Joining Data

Often, data is split across multiple tables or files. Pandas lets you **combine** them just like SQL — or even more flexibly!

---

## Sample DataFrames

```python
employees = pd.DataFrame({
    "EmpID": [1, 2, 3],
    "Name": ["Alice", "Bob", "Charlie"],
    "DeptID": [10, 20, 30]
})

departments = pd.DataFrame({
    "DeptID": [10, 20, 40],
    "DeptName": ["HR", "Engineering", "Marketing"]
})
```

---

## Merge Like SQL: `pd.merge()`

### Inner Join (default)

```python
pd.merge(employees, departments, on="DeptID")
```

Returns only matching DeptIDs:

| EmpID | Name    | DeptID | DeptName    |
|--------|---------|--------|-------------|
| 1      | Alice   | 10     | HR          |
| 2      | Bob     | 20     | Engineering |

---

### Left Join

```python
pd.merge(employees, departments, on="DeptID", how="left")
```

Keeps all employees, fills `NaN` where no match.

---

### Right Join

```python
pd.merge(employees, departments, on="DeptID", how="right")
```

Keeps all departments, even if no employee.

---

### Outer Join

```python
pd.merge(employees, departments, on="DeptID", how="outer")
```

Includes *all* data, fills missing with `NaN`.


---

## Concatenating DataFrames

Use `pd.concat()` to **stack** datasets either vertically or horizontally.

### Vertical (rows)

```python
df1 = pd.DataFrame({"Name": ["Alice", "Bob"]})
df2 = pd.DataFrame({"Name": ["Charlie", "David"]})

pd.concat([df1, df2])
```

### Horizontal (columns)

```python
df1 = pd.DataFrame({"ID": [1, 2]})
df2 = pd.DataFrame({"Score": [90, 80]})

pd.concat([df1, df2], axis=1)
```

> Make sure indexes align when using `axis=1`

---

## When to Use What?

| Use Case                        | Method     |
|---------------------------------|------------|
| SQL-style joins (merge keys)    | `pd.merge()` or `.join()` |
| Stack datasets vertically       | `pd.concat([df1, df2])`   |
| Combine different features side-by-side | `pd.concat([df1, df2], axis=1)` |
| Align on index                 | `.join()` or merge with `right_index=True` |

---

## Summary

- Use `merge()` like SQL joins (`inner`, `left`, `right`, `outer`)  
- Use `concat()` to stack DataFrames (rows or columns)  
- Handle mismatched keys and indexes with care  
- Merging and joining are essential for real-world projects

In [1]:
import pandas as pd

In [2]:
employees = pd.DataFrame({
    "EmpID": [1, 2, 3],
    "Name": ['Komal', 'Bhavesh', 'Shreya'],
    "DeptID": [10, 20, 30]
})

In [3]:
employees

   EmpID     Name  DeptID
0      1    Komal      10
1      2  Bhavesh      20
2      3   Shreya      30

In [4]:
departments = pd.DataFrame({
    "DeptID": [10, 20, 40],
    "DeptName": ['Engineering', 'Marketing', 'HR']
})

In [5]:
departments

   DeptID     DeptName
0      10  Engineering
1      20    Marketing
2      40           HR

# Merge Like SQL: `pd.merge()`

## Inner Join (default)

In [6]:
pd.merge(employees, departments, on='DeptID')   # Inner Join

   EmpID     Name  DeptID     DeptName
0      1    Komal      10  Engineering
1      2  Bhavesh      20    Marketing

## Left Join

In [7]:
pd.merge(employees, departments, on='DeptID', how='left')   # Left Join

   EmpID     Name  DeptID     DeptName
0      1    Komal      10  Engineering
1      2  Bhavesh      20    Marketing
2      3   Shreya      30          NaN

## Right Join

In [8]:
pd.merge(employees, departments, on='DeptID', how='right')   # Right Join

   EmpID     Name  DeptID     DeptName
0    1.0    Komal      10  Engineering
1    2.0  Bhavesh      20    Marketing
2    NaN      NaN      40           HR

## Outer Join

In [9]:
pd.merge(employees, departments, on='DeptID', how='outer')   # Outer Join

   EmpID     Name  DeptID     DeptName
0    1.0    Komal      10  Engineering
1    2.0  Bhavesh      20    Marketing
2    3.0   Shreya      30          NaN
3    NaN      NaN      40           HR

# Concatenating DataFrames

### Use `pd.concat()` to stack datasets either vertically or horizontally.

- ### Vertical (rows)

In [10]:
df1 = pd.DataFrame({"Name": ['Komal', 'Bhavesh']})
df2 = pd.DataFrame({"Name": ['Shreya', 'Namrata']})

In [46]:
pd.concat([df1, df2])

      Name
0    Komal
1  Bhavesh
0   Shreya
1  Namrata

- ### Horizontal (columns)

In [40]:
df3 = pd.DataFrame({"ID": [1, 2]})
df4 = pd.DataFrame({"Score": [90, 80]})

In [45]:
pd.concat([df3, df4], axis=1)

   ID  Score
0   1     90
1   2     80

---

In [50]:
new_df1 = pd.DataFrame({"Name": ['Yash', 'Hitesh'], "Score": [244, 210]})
new_df2 = pd.DataFrame({"Name": ['Jay', 'Pranav'], "Age": [23, 20]})

In [51]:
new_df1

     Name  Score
0    Yash    244
1  Hitesh    210

In [52]:
new_df2

     Name  Age
0     Jay   23
1  Pranav   20

In [53]:
pd.concat([new_df1, new_df2])

     Name  Score   Age
0    Yash  244.0   NaN
1  Hitesh  210.0   NaN
0     Jay    NaN  23.0
1  Pranav    NaN  20.0

In [54]:
pd.concat([new_df1, new_df2], axis=1)

     Name  Score    Name  Age
0    Yash    244     Jay   23
1  Hitesh    210  Pranav   20