# Reading & Writing Files in Pandas

## CSV Files

### Read CSV
```python
df = pd.read_csv("data.csv")
```

Options:
```python
pd.read_csv("data.csv", usecols=["Name", "Age"], nrows=10)
```

### Write CSV
```python
df.to_csv("output.csv", index=False)
```

---

## Excel Files

### Read Excel
```python
df = pd.read_excel("data.xlsx")
```

Options:
```python
pd.read_excel("data.xlsx", sheet_name="Sales")
```

### Write Excel
```python
df.to_excel("output.xlsx", index=False)
```

Multiple sheets:
```python
with pd.ExcelWriter("report.xlsx") as writer:
    df1.to_excel(writer, sheet_name="Summary", index=False)
    df2.to_excel(writer, sheet_name="Details", index=False)
```

---

## JSON Files

### Read JSON
```python
df = pd.read_json("data.json")
```


## Summary

- `read_*` and `to_*` methods for CSV, Excel, JSON
- Use `sheet_name` for Excel

In [1]:
import pandas as pd

## CSV Files

In [2]:
df = pd.read_csv('data2.csv')

In [3]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [6]:
df2 = df[df['Genre'] == 'Action'].copy()

In [7]:
df2

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
7,Hrithik Roshan,War,2019,Action,475,6.5
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [8]:
df2.to_csv('action_movies.csv', index=False)

## Excel Files

In [14]:
df3 = df[(df['Year'] >= 2019) & (df['Year'] <= 2022)].copy()

In [15]:
df3

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [16]:
df3.to_excel('2019_to_2022_movies.xlsx', index=False)

### You can write multiple sheets -
#### For Example:
```python
with pd.ExcelWriter("report.xlsx") as writer:
    df1.to_excel(writer, sheet_name="Summary", index=False)
    df2.to_excel(writer, sheet_name="Details", index=False)
```

## JSON Files

In [17]:
df_json = pd.read_json('my.json')

In [18]:
df_json

   id     name                                address
0   1     Yash   {'city': 'Delhi', 'zipcode': 110001}
1   2  Bhavesh  {'city': 'Mumbai', 'zipcode': 400001}

In [19]:
df_json.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       2 non-null      int64
 1   name     2 non-null      object
 2   address  2 non-null      object
dtypes: int64(1), object(2)
memory usage: 180.0+ bytes

In [21]:
data = [
    {
        "id": 1,
        "name": "Yash",
        "address": {
            "city": "Delhi",
            "zipcode": 110001
        }
    },
    {
        "id": 2,
        "name": "Bhavesh",
        "address": {
            "city": "Mumbai",
            "zipcode": 400001
        }
    }
]

In [22]:
df_json = pd.json_normalize(data)

In [23]:
df_json

   id     name address.city  address.zipcode
0   1     Yash        Delhi           110001
1   2  Bhavesh       Mumbai           400001

In [24]:
df_json.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               2 non-null      int64
 1   name             2 non-null      object
 2   address.city     2 non-null      object
 3   address.zipcode  2 non-null      int64
dtypes: int64(2), object(2)
memory usage: 196.0+ bytes