In [1]:
import os
os.environ['OMP_NUM_THREADS'] = '1'

In [2]:
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.tree import DecisionTreeClassifier

In [3]:
data = pd.DataFrame({
    "MonthlyCharges":[30,35,40,70,75,80],
    "Tenure":[2,3,5,20,25,30],
    "Churn":[1,1,1,0,0,0]
})

In [4]:
data

   MonthlyCharges  Tenure  Churn
0              30       2      1
1              35       3      1
2              40       5      1
3              70      20      0
4              75      25      0
5              80      30      0

---

In [5]:
X = data[["MonthlyCharges","Tenure"]]
y = data["Churn"]

---

In [6]:
# unsupervised
kmeans = KMeans(n_clusters=3, random_state=42)
kmeans = kmeans.fit(X)

data["Cluster"] = kmeans.labels_

In [7]:
data

   MonthlyCharges  Tenure  Churn  Cluster
0              30       2      1        2
1              35       3      1        2
2              40       5      1        0
3              70      20      0        1
4              75      25      0        1
5              80      30      0        1

---

In [8]:
# supervised
model = DecisionTreeClassifier()
model = model.fit(X,y)

# prediction = model.predict([[65,18]])
prediction_data = pd.DataFrame([[65, 18]], columns=['MonthlyCharges', 'Tenure'])  # changed to match training features
prediction = model.predict(prediction_data)

print(f"Prediction: {prediction}")

Prediction: [0]