In [1]:
import os
os.environ['OMP_NUM_THREADS'] = '1'

In [2]:
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.tree import DecisionTreeClassifier

In [3]:
data = pd.DataFrame({
    "Experience":[1,2,3,8,10,12],
    "Score":[55,60,65,90,92,95],
    "Promotion":["No","No","No","Yes","Yes","Yes"]
})

In [4]:
data

   Experience  Score Promotion
0           1     55        No
1           2     60        No
2           3     65        No
3           8     90       Yes
4          10     92       Yes
5          12     95       Yes

---

In [5]:
X = data[["Experience","Score"]]
y = data["Promotion"]

---

In [6]:
kmeans = KMeans(n_clusters=2, random_state=42)
kmeans = kmeans.fit(X)

data["Cluster"]=kmeans.labels_

In [7]:
data

   Experience  Score Promotion  Cluster
0           1     55        No        0
1           2     60        No        0
2           3     65        No        0
3           8     90       Yes        1
4          10     92       Yes        1
5          12     95       Yes        1

---

In [8]:
model = DecisionTreeClassifier()
# model = model.fit(X,y)
model = model.fit(X.values, y.values)

prediction = model.predict([[7,88]])

print(f"Prediction: {prediction}")

Prediction: ['Yes']