In [1]:
import os
os.environ['OMP_NUM_THREADS'] = '1'

In [2]:
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.tree import DecisionTreeClassifier

In [3]:
data = pd.DataFrame({
    "Amount":[200,300,400,8000,9000,12000],
    "Frequency":[2,3,5,15,18,20],
    "Fraud":[0,0,0,1,1,1]
})

In [4]:
data

   Amount  Frequency  Fraud
0     200          2      0
1     300          3      0
2     400          5      0
3    8000         15      1
4    9000         18      1
5   12000         20      1

---

In [5]:
X=data[["Amount","Frequency"]]
y=data["Fraud"]

---

In [6]:
kmeans = KMeans(n_clusters=3, random_state=42)
kmeans = kmeans.fit(X)

data["Risk"]=kmeans.labels_

In [7]:
data

   Amount  Frequency  Fraud  Risk
0     200          2      0     0
1     300          3      0     0
2     400          5      0     0
3    8000         15      1     2
4    9000         18      1     2
5   12000         20      1     1

---

In [8]:
model = DecisionTreeClassifier()
model = model.fit(X.values, y.values)

prediction = model.predict([[9500,17]])

print(f"Prediction: {prediction}")

Prediction: [1]