In [1]:
import os
os.environ['OMP_NUM_THREADS'] = '1'

In [2]:
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.tree import DecisionTreeClassifier

In [3]:
data = pd.DataFrame({
    "Time":[5,6,8,30,35,40],
    "Purchase":[500,700,900,6000,7000,9000],
    "BuyAgain":[0,0,0,1,1,1]
})

In [4]:
data

   Time  Purchase  BuyAgain
0     5       500         0
1     6       700         0
2     8       900         0
3    30      6000         1
4    35      7000         1
5    40      9000         1

---

In [5]:
X = data[["Time","Purchase"]]
y = data["BuyAgain"]

---

In [6]:
kmeans = KMeans(n_clusters=2, random_state=42)
kmeans = kmeans.fit(X)

data["Cluster"]=kmeans.labels_

In [7]:
data

   Time  Purchase  BuyAgain  Cluster
0     5       500         0        0
1     6       700         0        0
2     8       900         0        0
3    30      6000         1        1
4    35      7000         1        1
5    40      9000         1        1

---

In [8]:
model = DecisionTreeClassifier()
model = model.fit(X.values, y.values)

prediction = model.predict([[32,6500]])

print(f"Prediction: {prediction}")

Prediction: [1]