In [1]:
import os
os.environ['OMP_NUM_THREADS'] = '1'

In [2]:
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.tree import DecisionTreeClassifier

In [3]:
data = pd.DataFrame({
    "Age":[22,28,35,60,70,80],
    "BP":[110,115,120,160,170,180],
    "Admission":[0,0,0,1,1,1]
})

In [4]:
data

   Age   BP  Admission
0   22  110          0
1   28  115          0
2   35  120          0
3   60  160          1
4   70  170          1
5   80  180          1

---

In [5]:
X = data[["Age","BP"]]
y = data["Admission"]

---

In [6]:
kmeans = KMeans(n_clusters=2, random_state=42)
kmeans = kmeans.fit(X)

data["Cluster"] = kmeans.labels_

In [7]:
data

   Age   BP  Admission  Cluster
0   22  110          0        0
1   28  115          0        0
2   35  120          0        0
3   60  160          1        1
4   70  170          1        1
5   80  180          1        1

---

In [8]:
model = DecisionTreeClassifier()
model = model.fit(X.values, y.values)

prediction = model.predict([[65,165]])

print(f"Prediction: {prediction}")

Prediction: [1]