In [1]:
import pandas as pd

In [2]:
employees = pd.DataFrame({
    "employee_id": [3, 90, 9, 60, 49, 43],
    "name": ["Bob", "Alice", "Tatiana", "Annabelle", "Jonathan", "Khaled"],
    "department": [
        "Operations",
        "Sales",
        "Engineering",
        "InformationTechnology",
        "HumanResources",
        "Administration"
    ],
    "salary": [48675, 11096, 33805, 37678, 23793, 40454]
})

In [3]:
employees

   employee_id       name             department  salary
0            3        Bob             Operations   48675
1           90      Alice                  Sales   11096
2            9    Tatiana            Engineering   33805
3           60  Annabelle  InformationTechnology   37678
4           49   Jonathan         HumanResources   23793
5           43     Khaled         Administration   40454

---

In [4]:
def selectFirstRows(employees):
    return employees.head(3)

In [5]:
selectFirstRows(employees)

   employee_id     name   department  salary
0            3      Bob   Operations   48675
1           90    Alice        Sales   11096
2            9  Tatiana  Engineering   33805