In [1]:
import pandas as pd

In [2]:
employees = pd.DataFrame({
    "name": ["Piper", "Grace", "Georgia", "Willow", "Finn", "Thomas"],
    "salary": [4548, 28150, 1103, 6593, 74576, 24433]
})

In [3]:
employees

      name  salary
0    Piper    4548
1    Grace   28150
2  Georgia    1103
3   Willow    6593
4     Finn   74576
5   Thomas   24433

---

In [4]:
def createBonusColumn(employees: pd.DataFrame) -> pd.DataFrame:
    employees['column'] = employees['salary'] * 2
    return employees

In [5]:
createBonusColumn(employees)

      name  salary  column
0    Piper    4548    9096
1    Grace   28150   56300
2  Georgia    1103    2206
3   Willow    6593   13186
4     Finn   74576  149152
5   Thomas   24433   48866