In [1]:
import pandas as pd

In [2]:
students = pd.DataFrame({
    "student_id": [32, 217, 779, 849],
    "name": ["Piper", None, "Georgia", "Willow"],
    "age": [5, 19, 20, 14]
})

In [3]:
students

   student_id     name  age
0          32    Piper    5
1         217     None   19
2         779  Georgia   20
3         849   Willow   14

---

In [4]:
def dropMissingData(students):
    return students.dropna(subset='name')

In [5]:
dropMissingData(students)

   student_id     name  age
0          32    Piper    5
2         779  Georgia   20
3         849   Willow   14