In [1]:
import pandas as pd

In [2]:
students = pd.DataFrame({
    "id": [1, 2, 3, 4, 5],
    "first": ["Mason", "Ava", "Taylor", "Georgia", "Thomas"],
    "last": ["King", "Wright", "Hall", "Thompson", "Moore"],
    "age": [6, 7, 16, 18, 10]
})

In [3]:
students

   id    first      last  age
0   1    Mason      King    6
1   2      Ava    Wright    7
2   3   Taylor      Hall   16
3   4  Georgia  Thompson   18
4   5   Thomas     Moore   10

---

In [4]:
def renameColumns(students: pd.DataFrame) -> pd.DataFrame:
    students = students.rename(
        columns = {
            'id': 'student_id',
            'first': 'first_name',
            'last': 'last_name',
            'age': 'age_in_years'
        }
    )
    return students

In [5]:
renameColumns(students)

   student_id first_name last_name  age_in_years
0           1      Mason      King             6
1           2        Ava    Wright             7
2           3     Taylor      Hall            16
3           4    Georgia  Thompson            18
4           5     Thomas     Moore            10