In [1]:
import pandas as pd

In [2]:
products = pd.DataFrame({
    "name": ["Wristwatch", "WirelessEarbuds", "GolfClubs", "Printer"],
    "quantity": [None, None, 779, 849],
    "price": [135, 821, 9319, 3051]
})

In [3]:
products

              name  quantity  price
0       Wristwatch       NaN    135
1  WirelessEarbuds       NaN    821
2        GolfClubs     779.0   9319
3          Printer     849.0   3051

---

In [4]:
def fillMissingValues(products: pd.DataFrame) -> pd.DataFrame:
    products['quantity'] = products['quantity'].fillna(0)
    return products

In [5]:
fillMissingValues(products)

              name  quantity  price
0       Wristwatch       0.0    135
1  WirelessEarbuds       0.0    821
2        GolfClubs     779.0   9319
3          Printer     849.0   3051