In [1]:
import pandas as pd

In [2]:
df1 = pd.DataFrame({
    "student_id": [1, 2, 3, 4],
    "name": ["Mason", "Ava", "Taylor", "Georgia"],
    "age": [8, 6, 15, 17]
})

In [3]:
df1

   student_id     name  age
0           1    Mason    8
1           2      Ava    6
2           3   Taylor   15
3           4  Georgia   17

In [4]:
df2 = pd.DataFrame({
    "student_id": [5, 6],
    "name": ["Leo", "Alex"],
    "age": [7, 7]
})

In [5]:
df2

   student_id  name  age
0           5   Leo    7
1           6  Alex    7

---

In [6]:
def concatenateTables(df1, df2):
    return pd.concat([df1, df2], axis=0)

In [7]:
concatenateTables(df1, df2)

   student_id     name  age
0           1    Mason    8
1           2      Ava    6
2           3   Taylor   15
3           4  Georgia   17
0           5      Leo    7
1           6     Alex    7