In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({
    "product": ["Umbrella", "SleepingBag"],
    "quarter_1": [417, 800],
    "quarter_2": [224, 936],
    "quarter_3": [379, 93],
    "quarter_4": [611, 875]
})

In [3]:
df

       product  quarter_1  quarter_2  quarter_3  quarter_4
0     Umbrella        417        224        379        611
1  SleepingBag        800        936         93        875

---

In [4]:
def meltTable(report):
    return report.melt(
        id_vars = 'product',
        value_vars= ['quarter_1', 'quarter_2', 'quarter_3', 'quarter_4'],
        var_name= 'quarter',
        value_name= 'sales'
    )

In [5]:
meltTable(df)

       product    quarter  sales
0     Umbrella  quarter_1    417
1  SleepingBag  quarter_1    800
2     Umbrella  quarter_2    224
3  SleepingBag  quarter_2    936
4     Umbrella  quarter_3    379
5  SleepingBag  quarter_3     93
6     Umbrella  quarter_4    611
7  SleepingBag  quarter_4    875