# BeautifulSoup for Web Scraping

## 1. What is BeautifulSoup?
- **BeautifulSoup** is a Python library used to parse HTML and XML documents.
- It creates a **parse tree** from page content, making it easy to extract data.
- It is often used with `requests` to scrape websites.

---

## 2. Installing BeautifulSoup

Install both **`beautifulsoup4`** and a parser like **`lxml`**:

```bash
pip install beautifulsoup4 lxml
```

---

## 3. Creating a BeautifulSoup Object

### Example

```python
from bs4 import BeautifulSoup
import requests

url = "https://example.com"
response = requests.get(url)

soup = BeautifulSoup(response.text, "lxml")
```

- `response.text`: HTML content.
- `"lxml"`: A fast and powerful parser (you can also use `"html.parser"`).

---

## 4. Understanding the HTML Structure

BeautifulSoup treats the page like a tree.  
You can search and navigate through **tags**, **classes**, **ids**, and **attributes**.

Example HTML:

```html
<html>
  <body>
    <h1>Title</h1>
    <p class="description">This is a paragraph.</p>
    <a href="/page">Read more</a>
  </body>
</html>
```

---

## 5. Common Methods in BeautifulSoup

### 5.1 Accessing Elements

- Access the **first occurrence** of a tag:

```python
soup.h1
```

- Get the **text** inside a tag:

```python
soup.h1.text
```

### 5.2 `find()` Method

- Finds the **first matching** element:

```python
soup.find("p")
```

- Find a tag with specific attributes:

```python
soup.find("p", class_="description")
```

### 5.3 `find_all()` Method

- Finds **all matching** elements:

```python
soup.find_all("a")
```

### 5.4 Using `select()` and `select_one()`

- Select elements using **CSS selectors**.

```python
soup.select_one("p.description")
```

```python
soup.select("a")
```

---

## 6. Extracting Attributes

Get the value of an attribute, such as `href` from an `<a>` tag:

```python
link = soup.find("a")
print(link["href"])
```

Or using `.get()`:

```python
print(link.get("href"))
```

---

## 7. Traversing the Tree

- Access parent elements:

```python
soup.p.parent
```

- Access children elements:

```python
list(soup.body.children)
```

- Find the next sibling:

```python
soup.h1.find_next_sibling()
```

---

## 8. Handling Missing Elements Safely

Always check if an element exists before accessing it:

```python
title_tag = soup.find("h1")
if title_tag:
    print(title_tag.text)
else:
    print("Title not found")
```

---

## 9. Summary

- BeautifulSoup helps parse and navigate HTML easily.
- Use `.find()`, `.find_all()`, `.select()`, and `.select_one()` to locate data.
- Always inspect the website's structure before writing scraping logic.
- Combine BeautifulSoup with `requests` for full scraping workflows.

In [1]:
from bs4 import BeautifulSoup

In [2]:
with open('htmls/page1.html', "r") as f:
    content = f.read()

In [3]:
soup = BeautifulSoup(content, 'html.parser')

In [4]:
h3s = soup.find_all('h3')

In [5]:
h3s

[<h3><a href="a-light-in-the-attic_1000/index.html" title="A Light in the Attic">A Light in the ...</a></h3>,
 <h3><a href="tipping-the-velvet_999/index.html" title="Tipping the Velvet">Tipping the Velvet</a></h3>,
 <h3><a href="soumission_998/index.html" title="Soumission">Soumission</a></h3>,
 <h3><a href="sharp-objects_997/index.html" title="Sharp Objects">Sharp Objects</a></h3>,
 <h3><a href="sapiens-a-brief-history-of-humankind_996/index.html" title="Sapiens: A Brief History of Humankind">Sapiens: A Brief History ...</a></h3>,
 <h3><a href="the-requiem-red_995/index.html" title="The Requiem Red">The Requiem Red</a></h3>,
 <h3><a href="the-dirty-little-secrets-of-getting-your-dream-job_994/index.html" title="The Dirty Little Secrets of Getting Your Dream Job">The Dirty Little Secrets ...</a></h3>,
 <h3><a href="the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html" title="The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull">The Coming Woman: A ...</a></h3>,
 <h3><a href="the-boys-in-the-boat-nine-americans-and-their-epic-quest-for-gold-at-the-1936-berlin-olympics_992/index.html" title="The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics">The Boys in the ...</a></h3>,
 <h3><a href="the-black-maria_991/index.html" title="The Black Maria">The Black Maria</a></h3>,
 <h3><a href="starving-hearts-triangular-trade-trilogy-1_990/index.html" title="Starving Hearts (Triangular Trade Trilogy, #1)">Starving Hearts (Triangular Trade ...</a></h3>,
 <h3><a href="shakespeares-sonnets_989/index.html" title="Shakespeare's Sonnets">Shakespeare's Sonnets</a></h3>,
 <h3><a href="set-me-free_988/index.html" title="Set Me Free">Set Me Free</a></h3>,
 <h3><a href="scott-pilgrims-precious-little-life-scott-pilgrim-1_987/index.html" title="Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)">Scott Pilgrim's Precious Little ...</a></h3>,
 <h3><a href="rip-it-up-and-start-again_986/index.html" title="Rip it Up and Start Again">Rip it Up and ...</a></h3>,
 <h3><a href="our-band-could-be-your-life-scenes-from-the-american-indie-underground-1981-1991_985/index.html" title="Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991">Our Band Could Be ...</a></h3>,
 <h3><a href="olio_984/index.html" title="Olio">Olio</a></h3>,
 <h3><a href="mesaerion-the-best-science-fiction-stories-1800-1849_983/index.html" title="Mesaerion: The Best Science Fiction Stories 1800-1849">Mesaerion: The Best Science ...</a></h3>,
 <h3><a href="libertarianism-for-beginners_982/index.html" title="Libertarianism for Beginners">Libertarianism for Beginners</a></h3>,
 <h3><a href="its-only-the-himalayas_981/index.html" title="It's Only the Himalayas">It's Only the Himalayas</a></h3>]

---

In [6]:
for h3 in h3s:
    print(h3.find('a')['title'])

A Light in the Attic
Tipping the Velvet
Soumission
Sharp Objects
Sapiens: A Brief History of Humankind
The Requiem Red
The Dirty Little Secrets of Getting Your Dream Job
The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull
The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics
The Black Maria
Starving Hearts (Triangular Trade Trilogy, #1)
Shakespeare's Sonnets
Set Me Free
Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)
Rip it Up and Start Again
Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991
Olio
Mesaerion: The Best Science Fiction Stories 1800-1849
Libertarianism for Beginners
It's Only the Himalayas

---

In [19]:
articles = soup.select('article.product_pod')

In [33]:
for article in articles:
    title = article.find('h3').find('a')['title']
    # price = article.select_one('p.price_color').text[3:]
    price = article.select_one('p.price_color').text.split('£')[1]
    print(f'Title : {title}\nPrice : {price}')
    print('\n')
    # print(title)

Title : A Light in the Attic
Price : 51.77


Title : Tipping the Velvet
Price : 53.74


Title : Soumission
Price : 50.10


Title : Sharp Objects
Price : 47.82


Title : Sapiens: A Brief History of Humankind
Price : 54.23


Title : The Requiem Red
Price : 22.65


Title : The Dirty Little Secrets of Getting Your Dream Job
Price : 33.34


Title : The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull
Price : 17.93


Title : The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics
Price : 22.60


Title : The Black Maria
Price : 52.15


Title : Starving Hearts (Triangular Trade Trilogy, #1)
Price : 13.99


Title : Shakespeare's Sonnets
Price : 20.66


Title : Set Me Free
Price : 17.46


Title : Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)
Price : 52.29


Title : Rip it Up and Start Again
Price : 35.02


Title : Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991
Price : 57.25


Title : Olio
Price : 23.88


Title : Mesaerion: The Best Science Fiction Stories 1800-1849
Price : 37.59


Title : Libertarianism for Beginners
Price : 51.33


Title : It's Only the Himalayas
Price : 45.17

---

In [35]:
items = []

for article in articles:
    title = article.find('h3').find('a')['title']
    # price = article.select_one('p.price_color').text[3:]
    price = article.select_one('p.price_color').text.split('£')[1]
    items.append({"title": title, "price": price})

In [36]:
items

[{'title': 'A Light in the Attic', 'price': '51.77'},
 {'title': 'Tipping the Velvet', 'price': '53.74'},
 {'title': 'Soumission', 'price': '50.10'},
 {'title': 'Sharp Objects', 'price': '47.82'},
 {'title': 'Sapiens: A Brief History of Humankind', 'price': '54.23'},
 {'title': 'The Requiem Red', 'price': '22.65'},
 {'title': 'The Dirty Little Secrets of Getting Your Dream Job',
  'price': '33.34'},
 {'title': 'The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull',
  'price': '17.93'},
 {'title': 'The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics',
  'price': '22.60'},
 {'title': 'The Black Maria', 'price': '52.15'},
 {'title': 'Starving Hearts (Triangular Trade Trilogy, #1)', 'price': '13.99'},
 {'title': "Shakespeare's Sonnets", 'price': '20.66'},
 {'title': 'Set Me Free', 'price': '17.46'},
 {'title': "Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)",
  'price': '52.29'},
 {'title': 'Rip it Up and Start Again', 'price': '35.02'},
 {'title': 'Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991',
  'price': '57.25'},
 {'title': 'Olio', 'price': '23.88'},
 {'title': 'Mesaerion: The Best Science Fiction Stories 1800-1849',
  'price': '37.59'},
 {'title': 'Libertarianism for Beginners', 'price': '51.33'},
 {'title': "It's Only the Himalayas", 'price': '45.17'}]

---

In [37]:
import pandas as pd

In [50]:
df = pd.DataFrame(items)

In [51]:
df

                                                title  price
0                                A Light in the Attic  51.77
1                                  Tipping the Velvet  53.74
2                                          Soumission  50.10
3                                       Sharp Objects  47.82
4               Sapiens: A Brief History of Humankind  54.23
5                                     The Requiem Red  22.65
6   The Dirty Little Secrets of Getting Your Dream...  33.34
7   The Coming Woman: A Novel Based on the Life of...  17.93
8   The Boys in the Boat: Nine Americans and Their...  22.60
9                                     The Black Maria  52.15
10     Starving Hearts (Triangular Trade Trilogy, #1)  13.99
11                              Shakespeare's Sonnets  20.66
12                                        Set Me Free  17.46
13  Scott Pilgrim's Precious Little Life (Scott Pi...  52.29
14                          Rip it Up and Start Again  35.02
15  Our Band Could Be Your Life: Scenes from the A...  57.25
16                                               Olio  23.88
17  Mesaerion: The Best Science Fiction Stories 18...  37.59
18                       Libertarianism for Beginners  51.33
19                            It's Only the Himalayas  45.17

---
---

In [61]:
new_items = []

for article in articles:
    title = article.find('h3').find('a')['title']
    price = article.select_one('p.price_color').text.split('£')[1]
    rating_element = article.select_one('p.star-rating')
    rating = rating_element['class'][1]
    new_items.append([title, price, rating])

In [62]:
new_items

[['A Light in the Attic', '51.77', 'Three'],
 ['Tipping the Velvet', '53.74', 'One'],
 ['Soumission', '50.10', 'One'],
 ['Sharp Objects', '47.82', 'Four'],
 ['Sapiens: A Brief History of Humankind', '54.23', 'Five'],
 ['The Requiem Red', '22.65', 'One'],
 ['The Dirty Little Secrets of Getting Your Dream Job', '33.34', 'Four'],
 ['The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull',
  '17.93',
  'Three'],
 ['The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics',
  '22.60',
  'Four'],
 ['The Black Maria', '52.15', 'One'],
 ['Starving Hearts (Triangular Trade Trilogy, #1)', '13.99', 'Two'],
 ["Shakespeare's Sonnets", '20.66', 'Four'],
 ['Set Me Free', '17.46', 'Five'],
 ["Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)", '52.29', 'Five'],
 ['Rip it Up and Start Again', '35.02', 'Five'],
 ['Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991',
  '57.25',
  'Three'],
 ['Olio', '23.88', 'One'],
 ['Mesaerion: The Best Science Fiction Stories 1800-1849', '37.59', 'One'],
 ['Libertarianism for Beginners', '51.33', 'Two'],
 ["It's Only the Himalayas", '45.17', 'Two']]

---

In [66]:
new_df = pd.DataFrame(new_items, columns=['Book Title', 'Price', 'Rating'])

In [67]:
new_df

                                           Book Title  Price Rating
0                                A Light in the Attic  51.77  Three
1                                  Tipping the Velvet  53.74    One
2                                          Soumission  50.10    One
3                                       Sharp Objects  47.82   Four
4               Sapiens: A Brief History of Humankind  54.23   Five
5                                     The Requiem Red  22.65    One
6   The Dirty Little Secrets of Getting Your Dream...  33.34   Four
7   The Coming Woman: A Novel Based on the Life of...  17.93  Three
8   The Boys in the Boat: Nine Americans and Their...  22.60   Four
9                                     The Black Maria  52.15    One
10     Starving Hearts (Triangular Trade Trilogy, #1)  13.99    Two
11                              Shakespeare's Sonnets  20.66   Four
12                                        Set Me Free  17.46   Five
13  Scott Pilgrim's Precious Little Life (Scott Pi...  52.29   Five
14                          Rip it Up and Start Again  35.02   Five
15  Our Band Could Be Your Life: Scenes from the A...  57.25  Three
16                                               Olio  23.88    One
17  Mesaerion: The Best Science Fiction Stories 18...  37.59    One
18                       Libertarianism for Beginners  51.33    Two
19                            It's Only the Himalayas  45.17    Two

---

In [68]:
new_df.to_csv('data.csv', index=False)